version: '3.8'

services:
  fastapi:
    build: ./TraderieApi
    image: traderie_api_img   # ✅ 이미지 이름 설정
    container_name: traderie_api_app
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./CrawlResult:/app/CrawlResult  # 공유 폴더
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  crawler:
    build: ./TraderieCrawler
    image: traderie_crawler_img   # ✅ 이미지 이름 설정
    container_name: traderie_crawler_app
    ports:
      - "8001:8000"
    networks:
      - app-network
    volumes:
      - ./CrawlResult:/app/CrawlResult  # 공유 폴더

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: traderie_cloudflare
    restart: unless-stopped
    command: tunnel --url http://traderie_api_app:8000
    depends_on:
      fastapi:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
